<?php

namespace Omega\NAOBundle\Repository;

/**
 * ObservationsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObservationsRepository extends \Doctrine\ORM\EntityRepository
{
    public function RecupObservation ($espece)
    {
        $qb = $this->createQueryBuilder('a')
            ->where('a.espece = :espece')
            ->setParameter('espece', $espece);

        return $qb  ->getQuery()
                    ->getResult();

    }
    public function countObservation ($espece)
    {
        $qb = $this->createQueryBuilder('a')
            ->select('count(a)')
            ->where('a.espece = :espece')
            ->setParameter('espece', $espece);

        return $qb  ->getQuery()
            ->getSingleScalarResult();

    }
}
