<?php

namespace Omega\NAOBundle\Repository;

/**
 * TaxrefRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaxrefRepository extends \Doctrine\ORM\EntityRepository
{
    public function RecupEspece ($espece)
    {
        $qb = $this->createQueryBuilder('a')
            ->where('a.nomVern = :espece')
            ->setParameter('espece', $espece);

        return $qb  ->getQuery()
            ->getScalarResult();

    }
    public function countEspece ($espece)
    {
        $qb = $this->createQueryBuilder('a')
            ->select('count(a)')
            ->where('a.nomVern = :espece')
            ->setParameter('espece', $espece);

        return $qb  ->getQuery()
            ->getSingleScalarResult();

    }
	public function isNotEspece($espece)
	{
		$qb = $this->createQueryBuilder('t');
		$qb
		 ->where('t.nomVern = :espece')
		 ->setParameter('espece', $espece)
		 ;

		 return $qb
		 	->getQuery()
		 	->getResult()
		 ;
	}
}
