<?php

namespace Omega\NAOBundle\Repository;

/**
 * TaxrefRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaxrefRepository extends \Doctrine\ORM\EntityRepository
{
	public function isNotEspece($espece)
	{
		$qb = $this->createQueryBuilder('t');
		$qb
		 ->where('t.nomVern = :espece')
		 ->setParameter('espece', $espece)
		 ;

		 return $qb
		 	->getQuery()
		 	->getResult()
		 ;
	}
}
